// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxu9I3Hbrt7IzwVE3IW4_vGVWF6Syp93o',
    appId: '1:401286605230:android:ce05090e153bfc4f16c03f',
    messagingSenderId: '401286605230',
    projectId: 'enigma-3b934',
    databaseURL:
        'https://enigma-3b934-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'enigma-3b934.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhsrQxXRgF-Z1pTSogRZgK-I9bZuXu9w8',
    appId: '1:401286605230:ios:d419e645792ff15e16c03f',
    messagingSenderId: '401286605230',
    projectId: 'enigma-3b934',
    databaseURL:
        'https://enigma-3b934-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'enigma-3b934.appspot.com',
    androidClientId:
        '401286605230-tj76ru4jfmligjl0g4ln5uhqrqjg5vsk.apps.googleusercontent.com',
    iosClientId:
        '401286605230-27r60e4l88fb4c73ob503g93rnbu4ep7.apps.googleusercontent.com',
    iosBundleId: 'com.pocketdevs.enigma',
  );
}
