name: enigma
description: A Pocketdevs Development - Enigma
publish_to: "none"

version: 1.0.0+4

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.0.15

  provider: ^6.0.3
  firebase_core: ^1.20.0
  cloud_firestore: ^3.4.0
  firebase_auth: ^3.9.0
  firebase_storage: ^10.3.10

  persistent_bottom_nav_bar_v2: ^4.2.5
  step_progress_indicator: ^1.0.2
  timeago: ^3.3.0
  flutter_slidable: ^1.2.1
  cached_network_image: ^3.2.2
  flutter_tags_x: ^1.1.0
  flutter_keyboard_visibility: ^5.3.0
  group_button: ^5.2.2
  giphy_get: ^3.1.1
  flutter_svg: ^1.1.5
  shimmer: ^2.0.0

  # photo_gallery: ^1.1.1
  image_picker: ^0.8.5+3
  flutter_cache_manager: ^3.3.0
  flutter_dotenv: ^5.0.2
  # wechat_assets_picker: ^8.1.1

  cupertino_icons: ^1.0.2
  image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  image_path_android: "assets/images/icon.png"
  image_path_ios: "assets/images/icon.png"

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/images/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
