List<String> academicsSuggestions = [
  "Agriculture & Food Science",
  "Art & Architecture",
  "Biology & Life Sciences",
  "Business & Economics",
  "Chemistry",
  "Communication & Mass Media",
  "Cultural & Area Studies",
  "Dentistry & Oral Sciences",
  "Diversity, Equity & Inclusion",
  "Education",
  "Environment",
  "History",
  "Humanities",
  "Law & Criminal Justice",
  "LGBT & Gender Studies",
  "Library & Information Science",
  "Literature & Language",
  "Mathematics",
  "Medical",
  "Multidisciplinary",
  "Music & Performing Arts",
  "Nursing & Allied Health",
  "Physics",
  "Political Science",
  "Psychology",
  "Religion & Philosophy",
  "Science",
  "Sociology & Social Work",
  "Sports & Sports Medicine",
  "Technology & Engineering",
  "Vocational Studies"
];

List<String> sportsSuggestions = [
  "Archery",
  "Badminton",
  "Baseball",
  "Basketball",
  "Boxing",
  "Bowling",
  "Bungee Jumping",
  "Cricket",
  "Cycling",
  "Darts",
  "Fencing",
  "Figure Skating",
  "Fishing",
  "Flag Football",
  "Football",
  "Golf",
  "Gymnastics",
  "Hang Gliding",
  "Horseback Riding",
  "Ice Hockey",
  "Ice Skating",
  "Jet Skiing",
  "Judo",
  "Karate",
  "Kickboxing",
  "Pool",
  "Rock Climbing",
  "Roller Skating",
  "Rugby",
  "Scuba Diving",
  "Skateboarding",
  "Sky Diving",
  "Soccer",
  "Surfing",
  "Swimming",
  "Table Tennis",
  "Taekwondo",
  "Tennis",
  "Track and Field",
  "Ultimate Frisbee",
  "Volleyball",
  "Water Skiing",
  "Weight Lifting",
  "Wind Surfing",
];
